### ISSUE TITLE
Update fiddle features/keyboard-shortcuts/interception-from-main

### ISSUE THREAD

**Issue by Ethan-Arrowood** [microsoft/electron-cse-hackoverflow-engagement#12]
Template: [features/keyboard-shortcuts/interception-from-main](https://github.com/electron/electron/tree/master/docs/fiddles/features/keyboard-shortcuts/interception-from-main)

Rel: #6

> This task is for organizational and tracking purposes. Refer to the linked 'Rel:' issues for further details.

**Comment by tonyferrell** [comment]
PR: https://github.com/electron/electron/pull/29207
