### ISSUE TITLE
Update fiddle features/notifications/main

### ISSUE THREAD

**Issue by Ethan-Arrowood** [microsoft/electron-cse-hackoverflow-engagement#18]
Template: [features/notifications/main](https://github.com/electron/electron/tree/master/docs/fiddles/features/notifications/main)

Rel: #6

> This task is for organizational and tracking purposes. Refer to the linked 'Rel:' issues for further details.

**Comment by codefoster** [comment]
Took assignment since I just worked on notifications/renderer

**Comment by Ethan-Arrowood** [comment]
https://github.com/electron/electron/pull/29268
