### ISSUE TITLE
Update fiddle features/keyboard-shortcuts/global

### ISSUE THREAD

**Issue by Ethan-Arrowood** [microsoft/electron-cse-hackoverflow-engagement#24]
Template: [features/keyboard-shortcuts/global](https://github.com/electron/electron/tree/master/docs/fiddles/features/keyboard-shortcuts/global)

Rel: #6

> This task is for organizational and tracking purposes. Refer to the linked 'Rel:' issues for further details.

**Comment by tonyferrell** [comment]
PR: https://github.com/electron/electron/pull/29207
