### ISSUE TITLE
Update fiddle features/keyboard-shortcuts/local

### ISSUE THREAD

**Issue by Ethan-Arrowood** [microsoft/electron-cse-hackoverflow-engagement#27]
Template: [features/keyboard-shortcuts/local](https://github.com/electron/electron/tree/master/docs/fiddles/features/keyboard-shortcuts/local)

Rel: #6

> This task is for organizational and tracking purposes. Refer to the linked 'Rel:' issues for further details.

**Comment by tonyferrell** [comment]
PR: https://github.com/electron/electron/pull/29207

**Comment by tonyferrell** [comment]
I think I'll also add a fiddle for [Shortcuts within a browser window](http://beta.electronjs.org/docs/how-to/keyboard-shortcuts#shortcuts-within-a-browserwindow)
