### ISSUE TITLE
Update fiddle features/macos-dock-menu

### ISSUE THREAD

**Issue by Ethan-Arrowood** [microsoft/electron-cse-hackoverflow-engagement#28]
Template: [features/macos-dock-menu](https://github.com/electron/electron/tree/master/docs/fiddles/features/macos-dock-menu)

Rel: #6

> This task is for organizational and tracking purposes. Refer to the linked 'Rel:' issues for further details.

EDIT: Fixed template

**Comment by tonyferrell** [comment]
Don't know if there's a way to link this to [the PR in the electron repo](https://github.com/electron/electron/pull/29197).

**Comment by Ethan-Arrowood** [comment]
GitHub doesn't support cross-org linking yet but you can add it to the issue either in the first comment blurb or down here in a new comment.
