### ISSUE TITLE
Update fiddle features/offscreen-rendering

### ISSUE THREAD

**Issue by Ethan-Arrowood** [microsoft/electron-cse-hackoverflow-engagement#50]
Template: [features/offscreen-rendering](https://github.com/electron/electron/tree/master/docs/fiddles/features/offscreen-rendering)

Rel: #6

> This task is for organizational and tracking purposes. Refer to the linked 'Rel:' issues for further details.

**Comment by kevinhartman** [comment]
https://github.com/electron/electron/pull/29211
