### ISSUE TITLE
Update fiddle features/recent-documents

### ISSUE THREAD

**Issue by Ethan-Arrowood** [microsoft/electron-cse-hackoverflow-engagement#68]
Template: [features/recent-documents](https://github.com/electron/electron/tree/master/docs/fiddles/features/recent-documents)

Rel: #6

> This task is for organizational and tracking purposes. Refer to the linked 'Rel:' issues for further details.

**Comment by kevinhartman** [comment]
https://github.com/electron/electron/pull/29242
