### ISSUE TITLE
Update fiddle features/drag-and-drop

### ISSUE THREAD

**Issue by Ethan-Arrowood** [microsoft/electron-cse-hackoverflow-engagement#9]
Template: [features/drag-and-drop](https://github.com/electron/electron/tree/master/docs/fiddles/features/drag-and-drop)

Rel: #6

> This task is for organizational and tracking purposes. Refer to the linked 'Rel:' issues for further details.

**Comment by tonyferrell** [comment]
PR: https://github.com/electron/electron/pull/29200
